@startuml 02_packages
title Diagramme de packages

rectangle Papy_Robot{
    left to right direction
    package question
    package answer
    package information
}
actor User
actor Google_Map <<externe>>
actor Wikimedia <<externe>>

User -- question
User -- answer
question -- information
answer -- information
information -- Google_Map
information -- Wikimedia


@enduml