@startuml 03_UC_answer
title Cas d'utilisation "answer"

package answer{
    left to right direction
    (voir la reponse \n plan + anecdote) as reponse
    (voir un message d'erreur) as error
}

actor User

User -- reponse
User -- error

@enduml