@startuml 03_UC_information
title Cas d'utilisation "information"

package information{
    left to right direction
    (renvoyer un plan) as map
    (renvoyer une anecdote) as story
}
actor Google_Map <<externe>>
actor Wikimedia <<externe>>

map -- Google_Map
story -- Wikimedia



@enduml