@startuml 05_class
title Diagramme de classes

class question{
    Analyse_question()
    --
    keywords: String
}

class information{
    ask_gmap()
    ask_wiki()
    --
    formatted_address: String
    location: Tuple
    street_city: String
    story: String
}

class Answer{
    response()
    --
    intro: String
    introduce_story: String
    no_result: String
}


@enduml